const produtos = [
    {
        key: 1,
        name: "Red Eye Café",
        image: "/images/Ofertas/RedEye.jpg",
        offer: 71,
        originalp: (25.90).toFixed(2),
        type: "buy",
        text: "O café Red Eye é a escolha perfeita para quem busca um impulso extra de energia. Combinando a intensidade do espresso com a suavidade do café filtrado, o Red Eye oferece um sabor robusto e encorpado, ideal para começar o dia com pique total ou para enfrentar longas jornadas.",
        imagep: "/images/produtos/p1.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 2,
        name: "Café Gelado com Sorvete",
        image: "/images/Ofertas/cafeGeladoSorvete.jpg",
        offer: 18,
        originalp: (17.90).toFixed(2),
        type: "buy",
        text: "É a sobremesa perfeita para os amantes de café e sorvete. Uma combinação irresistível de espresso quente e sorvete gelado, que se complementam em uma explosão de sabores e texturas.",
        imagep: "/images/produtos/p2.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 3,
        name: "Café Bombom",
        image: "/images/Ofertas/cafeBombom.jpg",
        offer: 77,
        originalp: (15.00).toFixed(2),
        type: "buy",
        text: "O Café Bombom é uma experiência sensorial única, combinando a intensidade do café com a doçura do leite condensado em camadas visuais e gustativas irresistíveis. Uma bebida que agrada tanto aos amantes de café quanto aos apreciadores de doces.",
        imagep: "/images/produtos/p3.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 4,
        name: "Chai Latte",
        image: "/images/Ofertas/cafeEspeciariasIndianas.jpg",
        offer: 77,
        originalp: (25.00).toFixed(2),
        type: "buy",
        text: "O Chai Latte é uma bebida quente e reconfortante, originária da Índia, que combina a intensidade do chá preto com especiarias aromáticas e a cremosidade do leite. Uma explosão de sabores que aquece o corpo e a alma, perfeita para momentos de relaxamento e bem-estar.",
        imagep: "/images/produtos/p4.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 5,
        name: "Café Espresso",
        image: "/images/Ofertas/espresso.jpg",
        offer: 1,
        originalp: (104.75).toFixed(2),
        type: "buy",
        text: "O Café Espresso é a expressão máxima do sabor e aroma do café. Uma bebida intensa e encorpada, preparada sob alta pressão, que extrai o melhor dos grãos de café em uma pequena dose de pura energia e prazer.",
        imagep: "/images/produtos/p5.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 6,
        name: "Café com Colágeno",
        image: "/images/Ofertas/cafeColageno.png",
        offer: 96,
        originalp: (145.38).toFixed(2),
        type: "buy",
        text: "O Café com Colágeno é uma bebida funcional que combina os benefícios energéticos do café com as propriedades rejuvenescedoras do colágeno. Uma opção deliciosa e prática para quem busca cuidar da pele, cabelos, unhas e articulações, sem abrir mão do prazer de um bom café.",
        imagep: "/images/produtos/p6.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 7,
        name: "Café de Avelã",
        image: "/images/Ofertas/cafeAvela.jpg",
        offer: 93,
        originalp: (57.90).toFixed(2),
        type: "buy",
        text: "O Café de Avelã é uma bebida que combina a intensidade do café com a doçura e o aroma característico da avelã. Uma experiência sensorial única, que agrada tanto aos amantes de café quanto aos apreciadores de sabores mais doces e sofisticados.",
        imagep: "/images/produtos/p7.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 8,
        name: "Café Proteíco",
        image: "/images/Ofertas/proteicoWheyProtein.jpg",
        offer: 74,
        originalp: (9.90).toFixed(2),
        type: "buy",
        text: "O Café Proteico é uma bebida funcional que combina os benefícios energéticos do café com as propriedades nutritivas das proteínas. Uma opção prática e saborosa para quem busca energia, saciedade e recuperação muscular, ideal para atletas, praticantes de atividades físicas e pessoas com rotinas intensas.",
        imagep: "/images/produtos/p8.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 9,
        name: "Café Latte",
        image: "/images/Ofertas/latte.jpg",
        offer: 93,
        originalp: (5.97).toFixed(2),
        type: "buy",
        text: "O Café Latte é uma bebida clássica e popular, apreciada em todo o mundo. A combinação perfeita de espresso e leite vaporizado, com uma fina camada de espuma, resulta em uma bebida cremosa, suave e reconfortante. Ideal para começar o dia com leveza ou para um momento de relaxamento.",
        imagep: "/images/produtos/p9.jpeg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 10,
        name: "Café Maple",
        image: "/images/Ofertas/maple.jpg",
        offer: 58,
        originalp: (25.75).toFixed(2),
        type: "buy",
        text: "O Café Maple é uma bebida que captura a essência aconchegante do xarope de bordo (maple syrup), combinando-o com a intensidade do café. Uma experiência sensorial que evoca memórias de manhãs de outono e doces momentos de conforto.",
        imagep: "/images/produtos/p10.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 11,
        name: "Café com Cacau em Pó",
        image: "/images/Ofertas/cafeCacauPo.jpg",
        offer: 17,
        originalp: (26.00).toFixed(2),
        type: "buy",
        text: "O café com cacau em pó é uma bebida deliciosa e reconfortante que combina a intensidade do café com o sabor rico e aveludado do cacau. É uma ótima opção para quem procura uma bebida quente e saborosa para começar o dia ou para um momento de relaxamento.",
        imagep: "/images/produtos/p11.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 12,
        name: "Café com Lavanda",
        image: "/images/Ofertas/cafeLavanda.jpg",
        offer: 86,
        originalp: (46.90).toFixed(2),
        type: "buy",
        text: "O café com lavanda é uma bebida que combina a intensidade do café com o aroma floral e relaxante da lavanda. Uma experiência sensorial única, que proporciona um momento de calma e bem-estar.",
        imagep: "/images/produtos/p12.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 13,
        name: "Latte Macchiato",
        image: "/images/Ofertas/latteMacchiato.jpg",
        offer: 46,
        originalp: (14.99).toFixed(2),
        type: "buy",
        text: "O Latte Macchiato é uma bebida sofisticada e visualmente atraente, que se destaca por suas camadas distintas de leite quente, espresso e espuma de leite. Uma experiência sensorial que combina a suavidade do leite com a intensidade do café, perfeita para quem busca um momento de prazer e elegância.",
        imagep: "/images/produtos/p13.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 14,
        name: "Café com Amêndoas",
        image: "/images/Ofertas/cafeLicorAmendoas.jpg",
        offer: 89,
        originalp: (179.90).toFixed(2),
        type: "buy",
        text: "O café com amêndoas é uma bebida que combina a intensidade do café com o sabor suave e adocicado das amêndoas. Uma experiência sensorial única, que proporciona um momento de prazer e bem-estar.",
        imagep: "/images/produtos/p14.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 15,
        name: "Pingado",
        image: "/images/Ofertas/pingado.jpg",
        offer: 36,
        originalp: (33.36).toFixed(2),
        type: "buy",
        text: "O pingado é uma bebida clássica brasileira, apreciada em padarias e lares de todo o país. É uma combinação simples, mas perfeita, de café e leite, que aquece o corpo e a alma.",
        imagep: "/images/produtos/p15.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 16,
        name: "Cold Brew",
        image: "/images/Ofertas/coldBrew.jpg",
        offer: 36,
        originalp: (13.40).toFixed(2),
        type: "buy",
        text: "O cold brew é uma bebida de café gelada que se destaca por sua suavidade e sabor adocicado natural. Diferente do café gelado tradicional, que é preparado com café quente e resfriado, o cold brew é feito com infusão de café moído em água fria ou em temperatura ambiente, por um período prolongado de tempo.",
        imagep: "/images/produtos/p16.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 17,
        name: "Café Tia Maria",
        image: "/images/Ofertas/tiaMaria.jpg",
        offer: 61,
        originalp: (31.90).toFixed(2),
        type: "buy",
        text: "Tia Maria é um licor de café icônico, conhecido por sua combinação única de grãos de café jamaicanos, rum e baunilha. Uma bebida versátil e saborosa, perfeita para ser apreciada pura, com gelo ou como ingrediente em diversos coquetéis e sobremesas.",
        imagep: "/images/produtos/p17.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 18,
        name: "Espresso Martini",
        image: "/images/Ofertas/espressoMartini.jpg",
        offer: 75,
        originalp: (24.90).toFixed(2),
        type: "buy",
        text: "O Espresso Martini é um coquetel clássico e elegante, conhecido por sua combinação revigorante de café espresso, vodka e licor de café. Uma bebida perfeita para quem busca um toque de sofisticação e energia em um único gole.",
        imagep: "/images/produtos/p18.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 19,
        name: "Café Caramelo",
        image: "/images/Ofertas/caramelo.jpg",
        offer: 37,
        originalp: (14.99).toFixed(2),
        type: "buy",
        text: "O café caramelo é uma bebida que combina a intensidade do café com a doçura e o sabor característico do caramelo. Uma experiência sensorial única, que agrada tanto aos amantes de café quanto aos apreciadores de sabores mais doces e sofisticados.",
        imagep: "/images/produtos/p19.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 20,
        name: "Café Mexicano",
        image: "/images/Ofertas/mexicano.jpg",
        offer: 74,
        originalp: (18.82).toFixed(2),
        type: "buy",
        text: "O café mexicano é uma bebida que combina a intensidade do café com a riqueza de especiarias e, em algumas versões, o toque ousado da tequila ou do licor de café. Uma experiência sensorial que celebra a cultura mexicana e seus sabores vibrantes.",
        imagep: "/images/produtos/p20.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 21,
        name: "Espresso Tônica",
        image: "/images/maisVistos/expressoTonica.png",
        offer: 0,
        originalp: (14.99).toFixed(2),
        type: "buy",
        text: "O Espresso Tônica é um coquetel refrescante e energizante que combina a intensidade do café espresso com o sabor cítrico e borbulhante da água tônica. Uma bebida perfeita para os dias quentes ou para quem busca um estímulo extra com um toque de sofisticação.",
        imagep: "/images/produtos/p21.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 22,
        name: "Café Irlandês",
        image: "/images/maisVistos/irlandes.jpg",
        offer: 0,
        originalp: (23.24).toFixed(2),
        type: "buy",
        text: "O café irlandês é uma bebida quente e reconfortante que combina a intensidade do café com o calor do whisky irlandês e a doçura do açúcar, finalizada com uma camada de creme fresco. Uma experiência sensorial que aquece o corpo e a alma, perfeita para os dias frios ou para um momento de relaxamento.",
        imagep: "/images/produtos/p22.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
    {
        key: 23,
        name: "Café de Coco",
        image: "/images/maisVistos/cafeCoco.jpg",
        offer: 0,
        originalp: (22.70).toFixed(2),
        type: "buy",
        text: "O café de coco é uma bebida que transporta seus sentidos para um paraíso tropical, combinando a intensidade do café com a doçura e o aroma exótico do coco. Uma experiência sensorial única, que agrada tanto aos amantes de café quanto aos apreciadores de sabores tropicais.",
        imagep: "/images/produtos/p23.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)), },    
    {
        key: 24,
        name: "Café Sertanejo",
        image: "/images/maisVistos/sertanejoRapadura.jpg",
        offer: 0,
        originalp: (51.45).toFixed(2),
        type: "buy",
        text: "O café sertanejo é mais do que uma bebida, é uma experiência cultural que remonta às tradições do interior do Brasil. Ele representa a hospitalidade e o calor do povo sertanejo, sendo muitas vezes servido em grandes mesas com quitutes caseiros e ingredientes frescos da região.",
        imagep: "/images/produtos/p24.jpg",
        quantity: 50,
        buyed: Number((Math.random() * 100).toFixed(0)),
    },
]

export default produtos;